// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type {
  RootGetData,
  RootGetResponses,
  TestNeo4jTestNeo4jGetData,
  TestNeo4jTestNeo4jGetResponses,
} from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Root
 * Basic health check.
 */
export const rootGet = <ThrowOnError extends boolean = false>(
  options?: Options<RootGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    RootGetResponses,
    unknown,
    ThrowOnError
  >({
    url: '/',
    ...options,
  });
};

/**
 * Test Neo4J
 * Test Neo4j connection.
 */
export const testNeo4jTestNeo4jGet = <ThrowOnError extends boolean = false>(
  options?: Options<TestNeo4jTestNeo4jGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    TestNeo4jTestNeo4jGetResponses,
    unknown,
    ThrowOnError
  >({
    url: '/test-neo4j',
    ...options,
  });
};
