// This file is auto-generated by @hey-api/openapi-ts

export type RootHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health';
};

export type RootHealthGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};
