// This file is auto-generated by @hey-api/openapi-ts

export type RootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/';
};

export type RootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type TestNeo4jTestNeo4jGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/test-neo4j';
};

export type TestNeo4jTestNeo4jGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};
